import type { Metadata } from "next";
import "./globals.css";
import { cabin, coolveticaRg } from "@/public/fonts/fonts";

export const metadata: Metadata = {
  title: "🚀 Turning Ideas into Digital Reality",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#f9f5f2] ${cabin.variable} ${coolveticaRg.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
